title: Alexander Pickston
description: Learning the basics of how to generate a clean static website using GitHub Pages and the Cayman responsive theme, whilst also getting to grips with git.
theme: jekyll-theme-cayman
